name: shopping_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Các package hỗ trợ giao diện và điều hướng
  responsive_builder: ^0.7.0 # Giúp điều chỉnh giao diện theo kích thước màn hình
  go_router: ^12.0.0 # Hỗ trợ điều hướng tốt hơn cho web

  # Các package cần thiết
  curved_navigation_bar: ^1.0.6
  cloud_firestore:
  firebase_core:
  firebase_auth:
  random_string: ^2.3.1
  shared_preferences:
  image_picker:
  firebase_storage:
  flutter_stripe: ^11.3.0
  http:

  # Font và icon
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11



flutter:
  uses-material-design: true

  assets:
    - images/
